title: "Front View Future"
description: "A front-row seat to the most astonishing era in human history."
author: "Your Name"
url: ""
baseurl: ""

# Build
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Kramdown settings
kramdown:
  input: GFM
  math_engine: null
  syntax_highlighter: rouge

# Collections
collections:
  categories_pages:
    output: true
    permalink: /category/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
